ProcedureGroups <- list(
  Adults = list(
    Aortic = c("Freestyle ",
               "Ross ",
               "Aortic Valve Repair ",
               "AVR Mechanical ",
               "AVR Stented Bioprosthesis ",
               "Valve sparing Aortic Root Replacement ",
               "Homograft Aortic Root Replacement ",
               "Bentall ",
               "Ascending Aortic Replacement ",
               "Arch Replacement "),
    Mitral = c("Mitral Valve Repair ", "MVR Mechanical ", "MVR Stented Bioprosthesis "),
    Tricuspid = c("Tricuspid Valve Repair ", "TVR Mechanical ", "TVR Stented Bioprosthesis "),
    GUCH = c("Arterial switch ",
             "Rastelli ",
             "Extra anatomical Bypass of CoA ",
             "PAPVC Repair ",
             "AV Canal Repair Partial ",
             "Fallot Repair ",
             "VSD Closure ",
             "PVR Homograft ",
             "PVR Freestyle ",
             "PVR Stented Bioprosthesis ",
             "MPA Reconstruction ",
             "RPA Reconstruction ",
             "LPA Reconstruction ",
             "Pulmonary Valvotomy ",
             "Relief of RVOTO ",
             "RVOT Patch ",
             "Supravalvular AS Repair ",
             "Rupture Sinus of Valsalva Repair ",
             "Coronary AV Fistula Repair ",
             "Resection of Subaortic Membrane ",
             "Glenn ",
             "ASD Closure ",
             "Atrial Septectomy ",
             "Vascular Ring Repair ",
             "PDA Closure ",
             "MBT Shunt ",
             "PA Banding ")
  ),
  Pediatrics = list(
    TGA = c("Arterial switch ", "Atrial switch Mustard ", "Rastelli "),
    Arch = c("Arch Repair ", "Coarctectomy with extended end to end anastomosis "),
    Palliative = c("Glenn ", "DKS ", "Atrial Septectomy ", "MBT Shunt ",
                   "Central shunt ", "PA Banding ", "First Stage Switch PAB BTS ")
  )
)
