ProcedureGroups <- list(
  Adults = list(
    Aortic = c("Procedures..choice.Ross.",
               "Procedures..choice.Freestyle.",
               "Procedures..choice.Aortic.Valve.Repair.",
               "Procedures..choice.AVR..Mechanical..",
               "Procedures..choice.AVR..Stented.Bioprosthesis..",
               "Procedures..choice.Valve.sparing.Aortic.Root.Replacement.",
               "Procedures..choice.Homograft.Aortic.Root.Replacement.",
               "Procedures..choice.Bentall.",
               "Procedures..choice.Ascending.Aortic.Replacement.",
               "Procedures..choice.Arch.Replacement."),
    Mitral = c("Procedures..choice.Mitral.Valve.Repair.",
               "Procedures..choice.MVR..Mechanical..",
               "Procedures..choice.MVR..Stented.Bioprosthesis.."),
    Tricuspid = c("Procedures..choice.Tricuspid.Valve.Repair.",
                  "Procedures..choice.TVR..Mechanical..",
                  "Procedures..choice.TVR..Stented.Bioprosthesis.."),
    GUCH = c("Procedures..choice.Arterial.switch.",
             "Procedures..choice.Atrial.switch..Mustard..",
             "Procedures..choice.Rastelli.",
             "Procedures..choice.Coarctectomy.with.extended.end.to.end.anastomosis.",
             "Procedures..choice.Extra.anatomical.Bypass.of.CoA.",
             "Procedures..choice.PAPVC.Repair.",
             "Procedures..choice.AV.Canal.Repair..Transitional..",
             "Procedures..choice.AV.Canal.Repair..Partial..",
             "Procedures..choice.Fallot.Repair.",
             "Procedures..choice.VSD.Closure.",
             "Procedures..choice.Pulmonary.Valve.Replacement..Homograft..",
             "Procedures..choice.Pulmonary.Valve.Replacement..Freestyle..",
             "Procedures..choice.Pulmonary.Valve.Replacement..Stented.Bioprosthesis..",
             "Procedures..choice.MPA.Reconstruction.",
             "Procedures..choice.RPA.Reconstruction.",
             "Procedures..choice.LPA.Reconstruction.",
             "Procedures..choice.Pulmonary.Valvotomy.",
             "Procedures..choice.Pulmonary.Trans.annular.Patch.",
             "Procedures..choice.Relief.of.RVOTO.",
             "Procedures..choice.RVOT.Patch.",
             "Procedures..choice.Supravalvular.AS.Repair.",
             "Procedures..choice.Rupture.Sinus.of.Valsalva.Repair.",
             "Procedures..choice.Coronary.AV.Fistula.Repair.",
             "Procedures..choice.Resection.of.Subaortic.Membrane.",
             "Procedures..choice.Fontan.",
             "Procedures..choice.Glenn.",
             "Procedures..choice.ASD.Closure.",
             "Procedures..choice.Atrial.Septectomy.",
             "Procedures..choice.Cor.Triatriatum.Repair.",
             "Procedures..choice.Vascular.Ring.Repair.",
             "Procedures..choice.PDA.Closure.",
             "Procedures..choice.MBT.Shunt.",
             "Procedures..choice.Central.shunt.",
             "Procedures..choice.PA.Banding."),
    Closure = c("Procedures..choice.Chest.Closure.",
                "Procedures..choice.Rewiring.",
                "Procedures..choice.Wound.Debridement.")
  ),
  Pediatrics = list(
    TGA = c("Procedures..choice.Arterial.switch.",
            "Procedures..choice.Atrial.switch..Mustard..",
            "Procedures..choice.Rastelli."),
    Arch = c("Procedures..choice.Arch.Repair.",
             "Procedures..choice.Coarctectomy.with.extended.end.to.end.anastomosis.",
             "Procedures..choice.Extra.anatomical.Bypass.of.CoA."),
    Canal = c("Procedures..choice.AV.Canal.Repair..Complete..",
              "Procedures..choice.AV.Canal.Repair..Transitional..",
              "Procedures..choice.AV.Canal.Repair..Partial.."),
    Valvular = c("Procedures..choice.Ross.",
                 "Procedures..choice.Freestyle.",
                 "Procedures..choice.Aortic.Valve.Repair.",
                 "Procedures..choice.AVR..Mechanical..",
                 "Procedures..choice.AVR..Stented.Bioprosthesis..",
                 "Procedures..choice.Valve.sparing.Aortic.Root.Replacement.",
                 "Procedures..choice.Homograft.Aortic.Root.Replacement.",
                 "Procedures..choice.Bentall.",
                 "Procedures..choice.Mitral.Valve.Repair.",
                 "Procedures..choice.MVR..Mechanical..",
                 "Procedures..choice.MVR..Stented.Bioprosthesis..",
                 "Procedures..choice.Maze.Procedure.",
                 "Procedures..choice.Tricuspid.Valve.Repair.",
                 "Procedures..choice.TVR..Mechanical..",
                 "Procedures..choice.TVR..Stented.Bioprosthesis.."),
    RVOT_PA = c("Procedures..choice.Pulmonary.Valve.Replacement..Homograft..",
                "Procedures..choice.Pulmonary.Valve.Replacement..Freestyle..",
                "Procedures..choice.Pulmonary.Valve.Replacement..Stented.Bioprosthesis..",
                "Procedures..choice.MPA.Reconstruction.",
                "Procedures..choice.RPA.Reconstruction.",
                "Procedures..choice.LPA.Reconstruction.",
                "Procedures..choice.Pulmonary.Valvotomy.",
                "Procedures..choice.Pulmonary.Trans.annular.Patch.",
                "Procedures..choice.Relief.of.RVOTO.",
                "Procedures..choice.RVOT.Patch."),
    Palliative = c("Procedures..choice.Fontan.",
                   "Procedures..choice.Glenn.",
                   "Procedures..choice.DKS.",
                   "Procedures..choice.Atrial.Septectomy.",
                   "Procedures..choice.MBT.Shunt.",
                   "Procedures..choice.Central.shunt.",
                   "Procedures..choice.PA.Banding.",
                   "Procedures..choice.First.Stage.Switch..PAB..BTS..")
  )
)



# ProcedureGroups <- list(
#   Adults = list(
#     Aortic = c("Freestyle ",
#                "Ross ",
#                "Aortic Valve Repair ",
#                "AVR Mechanical ",
#                "AVR Stented Bioprosthesis ",
#                "Valve-sparing Aortic Root ",
#                "Homograft Aortic Root ",
#                "Bentall ",
#                "Ascending Aortic Replacement ",
#                "Arch Replacement "),
#     Mitral = c("Mitral Valve Repair ",
#                "MVR Mechanical ",
#                "MVR Stented Bioprosthesis "),
#     Tricuspid = c("Tricuspid Valve Repair ",
#                   "TVR Mechanical ",
#                   "TVR Stented Bioprosthesis "),
#     GUCH = c("Arterial switch ",
#              "Rastelli ",
#              "Extra anatomical Bypass of CoA ",
#              "PAPVC Repair ",
#              "AV Canal Repair Partial ",
#              "Fallot Repair ",
#              "VSD Closure ",
#              "PVR Homograft ",
#              "PVR Freestyle ",
#              "PVR Stented Bioprosthesis ",
#              "MPA Reconstruction ",
#              "RPA Reconstruction ",
#              "LPA Reconstruction ",
#              "Pulmonary Valvotomy ",
#              "Relief of RVOTO ",
#              "RVOT Patch ",
#              "Supravalvular AS Repair ",
#              "Rupture Sinus of Valsalva Repair ",
#              "Coronary AV Fistula Repair ",
#              "Resection of Subaortic Membrane ",
#              "Glenn ",
#              "ASD Closure ",
#              "Atrial Septectomy ",
#              "Vascular Ring Repair ",
#              "PDA Closure ",
#              "MBT Shunt ",
#              "PA Banding "),
#     Wound.Closure = c("Chest Closure ",
#                       "Rewiring ",
#                       "Wound Debridement ")
#   ),
#   Pediatrics = list(
#     TGA = c("Arterial switch ",
#             "Atrial switch Mustard ",
#             "Rastelli "),
#     Arch = c("Arch Repair ",
#              "CoA X-end-to-end "),
#     Canal = c("AV Canal Repair Complete ",
#                  "AV Canal Repair Transitional ",
#                  "AV Canal Repair Partial "),
#     Valvular = c("Ross ",
#                  "Freestyle ",
#                  "Aortic Valve Repair ",
#                  "AVR Mechanical ",
#                  "Mitral Valve Repair ",
#                  "MVR Mechanical ",
#                  "Maze Procedure ",
#                  "Tricuspid Valve Repair ",
#                  "TVR Mechanical ",
#                  "TVR Stented Bioprosthesis "),
#     RVOT_PA = c("PVR Homograft ",
#                 "PVR Freestyle ",
#                 "PVR Stented Bioprosthesis ",
#                 "MPA Reconstruction ",
#                 "RPA Reconstruction ",
#                 "LPA Reconstruction ",
#                 "Pulmonary Valvotomy ",
#                 "Pulmonary Trans-annular Patch ",
#                 "Relief of RVOTO ",
#                 "RVOT Patch "),
#     Palliative = c("Glenn ",
#                    "DKS ",
#                    "Atrial Septectomy ",
#                    "MBT Shunt ",
#                    "Central shunt ",
#                    "PA Banding ",
#                    "First Stage Switch PAB BTS ")
#   )
# )
