source("LoadDependencies.R")
source("Config.R")

source("ReorderColumns.R")
source("RemoveStepProcedures.R")
source("ImportCleanSave.R")
source("FilterBy.R")

source("TotalsTable.R")
source("AdultsPedsTable.R")
source("AgeGroupsTable.R")
source("GenderTable.R")
source("WeekDayTable.R")
source("CityTable.R")
source("ProceduresTable.R")
source("PlotProcedures.R")
source("RedoTable.R")
source("SurgeonTable.R")

source("WriteToExcel.R")
source("CreateTemplateFrom.R")
