source("LoadDependencies.R")
source("Config.R")

source("ExportFromRedcap.R")
source("ReorderColumns.R")
source("RemoveStepProcedures.R")
source("FixMortality.R")
source("ImportCleanSave.R")
source("FilterBy.R")
source("ProcedureGroups.R")
source("FixProcedureNames.R")
source("GetProcedureAssociations.R")

source("TotalsTable.R")
source("AdultsPedsTable.R")
source("AgeGroupsTable.R")
source("GenderTable.R")
source("WeekDayTable.R")
source("CityTable.R")
source("ProceduresTable.R")
source("PlotProcedures.R")
source("RedoTable.R")
source("SurgeonTable.R")
source("TrainersTable.R")
source("AdultsPedsMortalityTable.R")
source("AgeGroupsMortalityTable.R")
source("ProcedureMortalityTable.R")
source("SurgeonMortalityTable.R")
source("LengthOfStayTable.R")
source("PlotSurgeonProcedures.R")

source("SummaryTable.R")

source("WriteToExcel.R")
source("CreateTemplateFrom.R")
